### ISSUE TITLE
Expanded badge claim

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-badges#35]
@xmatthewx's mockup in mozilla/openbadges#947 contains several improvements to badge claiming that would really go in this codebase.

I think the main bits are:
- [ ] #36  1-2-3 claim flow
- [ ] #37 offer baked badge download
- [ ] #38 add social sharing from claim site (no backpack)
- [ ] #39 add embed instructions/snippet

I expect as we dive into these we'll see knock-on effects that require us to open other small tickets in `openbadger` and maybe other repositories, but I think those are the high-level items that could roughly be done independently of each other.

I would suggest we first build this with the assumption that all badges are hosted and coming from `openbadger` before generalizing for use in `badgekit`, or handling signed assertions, etc.

**Comment by threeqube** [comment]
Agreed. :+1:

**Comment by stenington** [comment]
@andrewhayward asks:

It looks great, I have two niggles with the flipping badge:

What happens if/when the 'brief description' is not brief enough?
- Do we lose text?
- Do we have a back that's bigger than the front?
- Something else?

The information is currently not keyboard accessible. It's a prototype, so not the end of the world, but we need to make sure that when we go into production these things are thought about.

**Comment by stenington** [comment]
So I think @xmatthewx's comment that the mockup is more UX than UI means all of these are valid questions that we'll spend time answering, and may very well end up moving away from the flip design, which is fine by me. It's flashy and neat, but not the best for accessibility so I'm fine ditching it, fwiw.

**Comment by stenington** [comment]
I'm going to ticket out the checklist items so each can be discussed in detail.

**Comment by iamjessklein** [comment]
:+1:
